---
# Intent is to standardize NTP configuration
- name: NTP Regional Servers
  cisco.ios.ios_ntp_global:
    config:
      servers:
        - server: "{{ ntp_servers[0] }}"
        - server: "{{ ntp_servers[1] }}"
        - server: "{{ ntp_servers[2] }}"
    state: replaced
