---
collections:
  - name: https://github.com/ansible-collections/cisco.ios
    type: git

  - name: https://github.com/ansible-collections/ansible.netcommon
    type: git

  # - name: https://github.com/cisco-en-programmability/dnacenter-ansible
  #   version: 6.13.3
  #   type: git
