---
# Delete old snmpv3 user accounts
# REQUIRES
  # cisco.ios.ios_facts:
  #   gather_network_resources:
  #     - snmp_server

- name: "SNMP user cleanup"
  cisco.ios.ios_config:
    lines: "no snmp-server user {{ snmp_user.username }} {{ snmp_user.group }} {{snmp_user.version }}"
  loop:
    "{{ ansible_facts.network_resources.snmp_server.users }}"
  loop_control:
    loop_var: snmp_user
  when: snmp_user.username not in 
    [ 'uARCPv3',
      'uPRIME2022',
      'uEOC-Riverbed2022',
      'uEOC-SolarWinds2022',
    ]
#  register: user_results

# - name: debug
#   ansible.builtin.debug:
#     msg: "{{ user_results }}"
