---
- name: Show
  hosts: all
  gather_facts: false

  tasks:
    - name: Show command
      cisco.ios.ios_command:
        commands:
          - "show run | inc command"
      register: output

    - name: Print output
      ansible.builtin.debug:
        # var: output.stdout_lines
        msg: "{{ output.stdout_lines }}"
